component_management:
  individual_components:
    - component_id: contracts
      name: contracts
      paths:
        - contracts

    - component_id: customer
      name: customer
      paths:
        - customer

    - component_id: issuer
      name: issuer
      paths:
        - issuer
