[package]
name = "zk_assets_rwa_1_hold_v1"
type = "bin"
authors = ["m374-crypt0"]
compiler_version = "1.0.0"
description = "evaluates RWA policy eligibility for managed assets"
entry = "src/main.nr"
license = "MIT"

[dependencies]
poseidon = { tag = "v0.3.0", git = "https://github.com/noir-lang/poseidon" }
