name: CI - Circuits

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "circuits/**"
  pull_request:
    paths:
      - "circuits/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install nargo
        run: |
          curl -L https://raw.githubusercontent.com/noir-lang/noirup/main/install | bash
          "$HOME/.nargo/bin/noirup"
          echo "$HOME/.nargo/bin" >> "$GITHUB_PATH"

      - name: Run circuit tests
        run: make circuits test
